### ISSUE TITLE
Starting broker with SpiffePrincipalBuilder raises org.apache.kafka.common.config.ConfigException

### ISSUE THREAD

**Issue by Benardi** [traiana/kafka-spiffe-principal#6]
## Setup
* Using kafka 2.4.1
  + Single zookeeper with the default configuration
  + Single broker with the following configuration

### Broker configuration

```ini
# server.properties
broker.id=0
port = 9092
zookeeper.connect=localhost:2181
advertised.host.name = kafka.lsd.ufcg.edu.br 
offsets.topic.replication.factor=1

security.protocol=SSL
ssl.client.auth=required
security.inter.broker.protocol = SSL
ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
listeners=SSL://kafka.lsd.ufcg.edu.br:9092
advertised.listeners=SSL://kafka.lsd.ufcg.edu.br:9092

# Stores
ssl.truststore.location=truststore.jks
ssl.truststore.password=123456
ssl.keystore.location=broker.keystore.jks
ssl.keystore.password=123456

# ACL related
authorizer.class.name=io.okro.kafka.SpiffePrincipalBuilder
# Disable host name checking
ssl.endpoint.identification.algorithm=
```

## Output
```bash
~/kafka_2.13-2.4.1$ bin/kafka-server-start.sh ./server.properties
[2021-03-24 12:11:46,757] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2021-03-24 12:11:47,474] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Authorizer does not implement org.apache.kafka.server.authorizer.Authorizer or kafka.security.auth.Authorizer .
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1185)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1122)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1102)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:34)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:29)
        at kafka.Kafka$.main(Kafka.scala:68)
        at kafka.Kafka.main(Kafka.scala)

```

**Comment by abhinavdangi** [comment]
Hello @Benardi, could you please explain the working of this jar along with Kafka properties?
It would be great if you could add this to README.md

**Comment by Benardi** [comment]
> Hello @Benardi, could you please explain the working of this jar along with Kafka properties?
> It would be great if you could add this to README.md

I've tried to add some explanations to the README in [this fork](https://github.com/ufcg-lsd/kafka-spiffe-principal). If you have a particular question, feel free to raise an issue there.

Beforehand, is there some part of the configuration you don't understand?

**Comment by royantman** [comment]
I no longer maintain this (not the repo owner/no longer in the org).
I am also certain you figured out the miss configuration.

But for anyone bumping into this:

```
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
principal.builder.class=io.okro.kafka.SpiffePrincipalBuilder
```

True for version 2.6.1, never tested on a newer version.
